# Generated by Django 5.0.4 on 2024-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp_Info",
            fields=[
                ("emp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=50)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("dept", models.CharField(max_length=20)),
            ],
        ),
    ]
